WIP: Scraped europython-2020
pyvideo/data pull request #1045
Opened 2020-11-14 10:52 UTC by gilgamezh

Pending to add speakers data and tags.

Fixes #1041

Event config:
~~~yaml
repo_dir: ../pyvideo_data

events:
- title: EuroPython2020
  dir: europython-2020
  youtube_list:
    - https://www.youtube.com/watch?v=CvbQArKEFes&list=PL8uoeex94UhHgMD9GOCbEHWku7pEPx9fW
  related_urls:
  - label: Conference schedule
    url: https://ep2020.europython.eu/schedule/
  - label: Conference Website
    url: https://ep2020.europython.eu/
  language: eng
  dates:
    begin: 2020-07-23
    end: 2020-07-26
    default: 2020-07-23
  issue: 1041
  minimal_download: false
  tags:
    - europython
    - europython-2020
    - europython-online
  overwrite:
    # all: true # takes precedence over add_new_files and existing_files_fields
    add_new_files: true
    existing_files_fields:
      - copyright_text
      - duration
      - thumbnail_url
      - videos
      - description
      - language
      - recorded
      - related_urls
      - speakers

~~~

Scraped with [pyvideo_scrape](https://github.com/pyvideo/pyvideo_scrape)

2020-11-28 18:49 UTC, logston requested changes
Great stuff here. Very thorough. Thank you! One request and then we can merge.

2020-11-28 18:49 UTC, logston commented on europython-2020/videos/aaron-ma-machine-learning-for-everyone.json
> +            "url": "/schedule/24-july?selected=8Tcrj4M-machine-learning-for-everyone"
Can we change these URLs to have a domain so that they are valid once published to PyVideo?

2021-06-28 02:33 UTC, logston commented
Hey @gilgamezh, thanks again for this. Can we get full URLs for the talks though?

2021-07-24 12:41 UTC, gilgamezh commented
Hello! sorry, this is in my backlog. I'll put some time after the 2021 conference. (or maybe during the sprints)
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Monday, June 28th, 2021 at 04:33, Paul Logston ***@***.***> wrote:

> Hey ***@***.***(https://github.com/gilgamezh), thanks again for this. Can we get full URLs for the talks though?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, [view it on GitHub](https://github.com/pyvideo/data/pull/1045#issuecomment-869293560), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AALNLJT25K2EHAMHRKYJY5LTU7NRPANCNFSM4TVPIQBQ).

2021-09-18 09:09 UTC, redapple commented
@logston , I did some changes to the URLs. can you have a 2nd look?

2021-09-18 21:41 UTC, logston commented
Sweet! Thanks!

2021-09-18 21:41 UTC, merged